name: Deploy to Performance Accelerator Prod Lightsail

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Publish .NET Core App
        run: dotnet publish -c Release -o release

      - name: Upload files to Lightsail
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_PUBLIC_IP }}
          username: Administrator
          key: ${{ secrets.LIGHTSAIL_SSH_PRIVATE_KEY }}
          source: "release/*"
          target: "C:\\temp\\performance-accelerator"

      - name: Deploy to IIS on Lightsail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_PUBLIC_IP }}
          username: Administrator
          key: ${{ secrets.LIGHTSAIL_SSH_PRIVATE_KEY }}
          script: |
            cmd /c "echo Checking source directory..."
            cmd /c "dir C:\temp\performance-accelerator\release\ /s"

            cmd /c "echo Ensuring deployment directory exists..."
            cmd /c "if not exist C:\inetpub\wwwroot\performance-accelerator mkdir C:\inetpub\wwwroot\performance-accelerator"

            cmd /c "echo Removing old files..."
            cmd /c "del /s /q C:\inetpub\wwwroot\performance-accelerator\*"

            cmd /c "echo Copying new files..."
            cmd /c "xcopy /E /I /Y C:\temp\performance-accelerator\release\* C:\inetpub\wwwroot\performance-accelerator\"

            cmd /c "echo Restarting IIS..."
            cmd /c "iisreset"
