name: Deploy to Performance Accelerator Prod Lightsail

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Publish .NET Core App
        run: dotnet publish -c Release -o release

      - name: Upload files to Lightsail
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_PUBLIC_IP }}
          username: Administrator
          key: ${{ secrets.LIGHTSAIL_SSH_PRIVATE_KEY }}
          source: "release/*"
          target: "C:\\temp\\performance-accelerator"

      - name: Deploy to IIS on Lightsail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_PUBLIC_IP }}
          username: Administrator
          key: ${{ secrets.LIGHTSAIL_SSH_PRIVATE_KEY }}
          script: |
            if (!(Test-Path "C:\inetpub\wwwroot\performance-accelerator")) { New-Item -ItemType Directory -Path "C:\inetpub\wwwroot\performance-accelerator" }
            Remove-Item -Recurse -Force "C:\inetpub\wwwroot\performance-accelerator\*"
            Copy-Item -Path "C:\temp\performance-accelerator\*" -Destination "C:\inetpub\wwwroot\performance-accelerator\" -Recurse
            iisreset
